version: "3.8"

services:
  jellyfin-tubearchivist-sync:
    build:
      context: .
      dockerfile: Dockerfile
    image: jellyfin-tubearchivist-sync:latest
    container_name: jellyfin-tubearchivist-sync
    restart: "no"
